export const ADD_OPERATION = 'ADD_OPERATION';
export const FETCH_OPERATIONS = 'FETCH_OPERATIONS';
export const REMOVE_OPERATION = 'REMOVE_OPERATION';
export const CLEAR_OPERATIONS = 'CLEAR_OPERATIONS';
