export const FETCH_OPERATIONS = 'FETCH_OPERATIONS';

export const CLEAR_OPERATIONS = 'CLEAR_OPERATIONS';

export const ADDING_OPERATION = 'ADDING_OPERATION';
export const ADDED_OPERATION = 'ADDED_OPERATION';
export const ADD_OPERATION_FAIL = 'ADD_OPERATION_FAIL';

export const REMOVING_OPERATION = 'REMOVING_OPERATION';
export const REMOVED_OPERATION = 'REMOVED_OPERATION';
export const REMOVE_OPERATION_FAIL = 'REMOVE_OPERATION_FAIL';
